spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:indra
    password:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
  servlet:
    multipart:
      max-file-size: 300MB
      max-request-size: 300MB
